config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  
  resources :users

    resources :doctors do
      resources :appointments
    end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :user
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :appointments
  has_many :users, through: :appointments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :appointments
  has_many :doctors, through: :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_doctor
  before_action :set_appointment, only: [:show, :edit, :delete]

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
  end

  def show
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.save
      redirect_to @appointment
    else
      render :new
    end
  end

  def edit
  end

  def delete
    @appointment.destroy
  end

  private

    def appointment_params
      params.require(:appointment).permit(:date)
    end
  
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def set_doctor
      @doctor = Doctor.find(params[:doctor_id])
    end
  end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :delete]
  def index
    @doctors = Doctor.all
  end

  def new
    @doctor = Doctor.new
  end

  def show
  end

  def create
    @doctor = Doctor.new(doctor_params)
    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def edit
  end

  def delete
    @doctor.destroy
  end

  private

    def doctor_params
      params.require(:doctor).permit(:name)
    end
  
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :delete]
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
  end

  def delete
    @user.destroy
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit

  end

  private

    def user_params
      params.require(:user).permit(:name, :phone_number)
    end

    def set_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/appointments/delete.html.erb
<h1>Appointments#delete</h1>
<p>Find me in app/views/appointments/delete.html.erb</p>

app/views/appointments/index.html.erb
<h1>Appointments#index</h1>
<p>Find me in app/views/appointments/index.html.erb</p>

app/views/appointments/new.html.erb
<h1>Make An Appointments</h1>
<%= form_for [@appointment, @doctor] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :date %>
  <%= f.text_field :date %>

  <%= f.submit %>
<% end %>

app/views/appointments/show.html.erb
<h1>Appointments#show</h1>
<p>Find me in app/views/appointments/show.html.erb</p>

app/views/doctors/delete.html.erb
<h1>Doctors#delete</h1>
<p>Find me in app/views/doctors/delete.html.erb</p>

app/views/doctors/index.html.erb
<h1>Doctors</h1>

<ul>
  <% @doctors.each do |doctor| %>
    <li><%= link_to doctor.name, doctor_path(doctor.id) %></li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1> Information </h1>
<p>Doctor's Name</p>
<br />
<p>Doctor's Credentials</p>
<p>Phone Number</p>

app/views/doctors/show.html.erb
<h1><%= @doctor.name %></h1>

<ul>
<li><%= link_to 'Schedule Appointment', new_doctor_appointment_path(@doctor.id) %></li>
<li><%= link_to 'Doctor Info', new_doctor_path %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsAppt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/delete.html.erb
<h1>Users#delete</h1>
<p>Find me in app/views/users/delete.html.erb</p>

app/views/users/index.html.erb
<h1>Users Page</h1>
<%= link_to 'List of Doctors', doctors_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>